version: '3.3'
services:
    db:
        image: postgres:11.5
        container_name: "az-db"
        environment:
            POSTGRES_DATABASE: az_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_ROOT_PASSWORD: rootpassword
        ports:
            - "3314:5432"
        volumes:
            - type: bind
              source: ./migrations/dev/init
              target: /docker-entrypoint-initdb.d
            - type: volume
              source: dbdata
              target: /var/lib/postgresql/data/

volumes: #Named volumes must be listed under the top-level volumes
  dbdata:
      driver: local