version: '3.3'
services:
    db:
        image: postgres:11.5
        container_name: "az-db"
        environment:
            POSTGRES_DATABASE: az_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_ROOT_PASSWORD: rootpassword
        ports:
            - "3314:5432"
        volumes:
            - ./migrations/dev:/docker-entrypoint-initdb.d

